package org.voegtle.privatetrainer.ui.theme

import androidx.compose.ui.graphics.Color

val privateLightPrimary = Color(0xFF825500)
val privateLightOnPrimary = Color(0xFFFFFFFF)
val privateLightPrimaryContainer = Color(0xFFFFDDAE)
val privateLightOnPrimaryContainer = Color(0xFF2A1800)
val privateLightSecondary = Color(0xFF6F5B40)
val privateLightOnSecondary = Color(0xFFFFFFFF)
val privateLightSecondaryContainer = Color(0xFFFADEBC)
val privateLightOnSecondaryContainer = Color(0xFF271904)
val privateLightTertiary = Color(0xFF516440)
val privateLightOnTertiary = Color(0xFFFFFFFF)
val privateLightTertiaryContainer = Color(0xFFD3EABC)
val privateLightOnTertiaryContainer = Color(0xFF102004)
val privateLightError = Color(0xFFBA1B1B)
val privateLightErrorContainer = Color(0xFFFFDAD4)
val privateLightOnError = Color(0xFFFFFFFF)
val privateLightOnErrorContainer = Color(0xFF410001)
val privateLightBackground = Color(0xFFFCFCFC)
val privateLightOnBackground = Color(0xFF1F1B16)
val privateLightSurface = Color(0xFFFCFCFC)
val privateLightOnSurface = Color(0xFF1F1B16)
val privateLightSurfaceVariant = Color(0xFFF0E0CF)
val privateLightOnSurfaceVariant = Color(0xFF4F4539)
val privateLightOutline = Color(0xFF817567)
val privateLightInverseOnSurface = Color(0xFFF9EFE6)
val privateLightInverseSurface = Color(0xFF34302A)
val privateLightPrimaryInverse = Color(0xFFFFB945)

val privateDarkPrimary = Color(0xFFFFB945)
val privateDarkOnPrimary = Color(0xFF452B00)
val privateDarkPrimaryContainer = Color(0xFF624000)
val privateDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val privateDarkSecondary = Color(0xFFDDC3A2)
val privateDarkOnSecondary = Color(0xFF3E2E16)
val privateDarkSecondaryContainer = Color(0xFF56442B)
val privateDarkOnSecondaryContainer = Color(0xFFFADEBC)
val privateDarkTertiary = Color(0xFFB8CEA2)
val privateDarkOnTertiary = Color(0xFF243516)
val privateDarkTertiaryContainer = Color(0xFF3A4C2B)
val privateDarkOnTertiaryContainer = Color(0xFFD3EABC)
val privateDarkError = Color(0xFFFFB4A9)
val privateDarkErrorContainer = Color(0xFF930006)
val privateDarkOnError = Color(0xFF680003)
val privateDarkOnErrorContainer = Color(0xFFFFDAD4)
val privateDarkBackground = Color(0xFF1F1B16)
val privateDarkOnBackground = Color(0xFFEAE1D9)
val privateDarkSurface = Color(0xFF1F1B16)
val privateDarkOnSurface = Color(0xFFEAE1D9)
val privateDarkSurfaceVariant = Color(0xFF4F4539)
val privateDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val privateDarkOutline = Color(0xFF9C8F80)
val privateDarkInverseOnSurface = Color(0xFF32281A)
val privateDarkInverseSurface = Color(0xFFEAE1D9)
val privateDarkPrimaryInverse = Color(0xFF624000)
